### ISSUE TITLE
GraphQL Servlet Bypassing API Interceptor

### ISSUE THREAD

**Issue by pclnzwang** [graphql-java/graphql-java-servlet#104]
https://github.com/graphql-java/graphql-spring-boot/issues/120

**Comment by pclnzwang** [comment]
<img width="1738" alt="screen shot 2018-09-13 at 15 38 13" src="https://user-images.githubusercontent.com/37309883/45511595-72310900-b76b-11e8-8494-2c14370a44de.png">


<img width="1751" alt="screen shot 2018-09-13 at 15 40 00" src="https://user-images.githubusercontent.com/37309883/45511601-752bf980-b76b-11e8-8258-a3ff263d496f.png">

**Comment by pclnzwang** [comment]
GraphQL-Java-Servlet should have some mechanism to apply interceptor chain before request reach to GraphQL controller.

**Comment by oliemansm** [comment]
Closing this issue since it seems to regard a Spring specific feature. See my comment in issue https://github.com/graphql-java/graphql-spring-boot/issues/120.
