### ISSUE TITLE
Bump graphql-java version if possible

### ISSUE THREAD

**Issue by dminkovsky** [graphql-java/graphql-java-servlet#12]
Per @jplock at https://github.com/graphql-java/graphql-java/issues/268#issuecomment-270201325. Thanks

**Comment by jplock** [comment]
My PR is kind of stuck...is there anyone else that can help?  This project seems abandoned.  :(

**Comment by dminkovsky** [comment]
Thanks for the ping. I will investigate tomorrow morning (EST)
