### ISSUE TITLE
Multipart usage

### ISSUE THREAD

**Issue by Vi-dot** [graphql-java/graphql-java-servlet#18]
Hello,

I saw in [GraphQLServletSpec.groovy (line 216)](https://github.com/graphql-java/graphql-java-servlet/blob/master/src/test/groovy/graphql/servlet/GraphQLServletSpec.groovy#L216) a java example of query by multipart.
But I tried with curl, and I get a 500 Error.
```
curl -v \
--request POST --url http://localhost:8080/graphql \
--header 'content-type: multipart/graphql' \
--form 'graphql={query: {test { test } }}'
```
What is wrong ?
Thx

**Comment by apottere** [comment]
It's possible graphql-java-servlet doesn't handle multipart correctly - I'll look into it.

**Comment by apottere** [comment]
I wasn't aware that `request.getPart()` only actually works in servlet 3.0 environments when multipart is explicitly turned on... I rewrote it using commons-fileupload and reworked the tests to actually test it with a content body instead of mocking out `Part`.

**Comment by apottere** [comment]
This is fixed in `2.1.0`.

**Comment by Vi-dot** [comment]
Thanks for your update.
But now I get a 400 Bad request : 
```
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /graphql HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 187
> Expect: 100-continue
> content-type: multipart/graphql; boundary=------------------------966f88642585a397
> 
< HTTP/1.1 100 Continue
< HTTP/1.1 400 Bad Request
< Date: Thu, 06 Apr 2017 08:10:26 GMT
< Content-Length: 0
< Server: Jetty(9.4.3.v20170317)
* HTTP error before end of send, stop sending
< 
* Closing connection 0
```
It may be because I use Jetty ?

**Comment by Vi-dot** [comment]
In fact you changed MIME type to multiplart/form-data, and you're right !
"graphql" as part key doesn't work with curl.
But it works fine with "query" key like this : 
```
curl -v --request POST \
--url http://localhost:8080/graphql \
--header 'Content-Type: multipart/form-data' \
--form 'query=query {test { test } }'
```

**Comment by apottere** [comment]
@Vi-dot Are you sure it doesn't work with `multipart/graphql`?  I was under the impression it just checked the first part.  Either way, when you send a "graphql" part, it has to be a JSON object since it can contain the query, variables, and operationName.  It should look the same as the POST body.

**Comment by Vi-dot** [comment]
@apottere 
Yes with curl & `multipart/graphql` as main Content-Type, it doesn't work.
Then why you also changed MIME type in [groovy test file there](https://github.com/graphql-java/graphql-java-servlet/commit/75f2e38e7cd6c60407c136e5f9c5c1e236698d2c#diff-ac879925f5c3e2f8735753428202eff6) ?

I think `multipart/form-data` is more appropriate for main Content-Type. About Content-Type of each part, it could be different.

**Comment by apottere** [comment]
Oh, I changed it because I think it's more appropriate too - I just thought it might still work.
