### ISSUE TITLE
GraphQLServlet not returning GraphQL response object on GraphQL errors

### ISSUE THREAD

**Issue by kellerb-b** [graphql-java/graphql-java-servlet#26]
Getting HTTP 400 error response from servlet when passing in invalid graphql query but structurally correct. No logging happening either.

Request:
{"query":"{ __schema{types{name}} }","ariables":"{}"}

Expected response to be something like:
{errors=[InvalidSyntaxError{sourceLocations=[SourceLocation{line=2, column=3}]}]}

HTTP 500 errors do not log stacktraces either. 

If this is intended behavior for the GraphQLServlet could you expose the ExecutionResult and the GraphQLRequest objects?

Thanks,
Barb Craig

**Comment by apottere** [comment]
I'm not sure that the expected response is correct for your first case.  Your query doesn't actually have any syntax errors, you just sent a bad request (variables => ariables).

As per not logging stacktraces, that seems like a bug.

**Comment by apottere** [comment]
It looks to me like the servlet should be logging on a 500:
```
response.setStatus(500);
log.error("Error executing GraphQL request!", t);
```

Do you have slf4j set up properly?

**Comment by apottere** [comment]
Check out https://github.com/graphql-java/graphql-java-servlet/blob/master/README.md#operation-and-servlet-listeners for getting access to the request/response/results
