### ISSUE TITLE
Support for Preparsed queries caching

### ISSUE THREAD

**Issue by aquarelius-** [graphql-java/graphql-java-servlet#39]
Hi, 
This may be rather a question then an issue. But just in case you guys decide to push it forward to implementation.

I am looking forward to the [Preparsed queries](https://github.com/graphql-java/graphql-java/issues/335) issue from graphql-java project been released. 
Are there any plans to provide support to that feature by graphql-java-servlet? Or could you please throw some light at how I may implement preparsed query caching myself without any specific support?

**Comment by apottere** [comment]
I haven't looked into that feature at all, but it seems like something that would have to be implemented in the servlet.  Do you have any examples of a preparsed request in another server and what a request would look like?

**Comment by raderio** [comment]
https://dev-blog.apollodata.com/persisted-graphql-queries-with-apollo-client-119fd7e6bba5
https://github.com/apollographql/persistgraphql

**Comment by raderio** [comment]
http://graphql-java.readthedocs.io/en/v4/execution.html#query-caching
