### ISSUE TITLE
Customise ObjectMapper capabilities

### ISSUE THREAD

**Issue by miguelaferreira** [graphql-java/graphql-java-servlet#42]
Is there a way to customise the object mapper used in the servlet. 
I'm having trouble serialising LocalDateTime objects, which can be solved by registering extra Jackson modules in the ObjectMapper.

Is there a way to achieve this?

**Comment by apottere** [comment]
I added an `ObjectMapperConfigurer` constructor parameter, but I also registered `Jdk8Module` by default so you shouldn't need to use it to fix your issue.

**Comment by miguelaferreira** [comment]
Great! Thanks
