### ISSUE TITLE
RFI: Asynchronous Servlet Support for long running queries.

### ISSUE THREAD

**Issue by cjemison** [graphql-java/graphql-java-servlet#44]
I was wondering if there will ever be support for asynchronous processing in the GraphlQLServlet? In the stack, I see a completeable futures.

**Comment by apottere** [comment]
The `4.x` line of graphql-java supports data fetchers that return CompletableFutures, but the servlet blocks for a response from graphql-java.  What would you want to see happen async in the servlet?

**Comment by cjemison** [comment]
Yes, the servlet is blocking. However, servlet 3.0+ supports asynchronous processing, allowing more connections during async processing. Do you mind if I submit a pr? You can add it if you like.

**Comment by apottere** [comment]
Yeah, definitely.

**Comment by cjemison** [comment]
Hi, I am swamped with my primary job right now. Will submit a PR when I have more time.

**Comment by apottere** [comment]
I know how you feel - take your time.

**Comment by SillyMoo** [comment]
Are you still open to a PR for this?
