### ISSUE TITLE
How to provide custom error messages to the client?

### ISSUE THREAD

**Issue by karl-run** [graphql-java/graphql-java-servlet#50]
Hi, I hope this isn't a too silly question.

I'm using graphql-java-tools, so I have a resolver that I would like to provide a nice error to the client from.

Example:
```
@Component
public class SomeMutationResolver implements GraphQLMutationResolver {

  @Autowired
  DataService DataService;

  public SomeObject addSomething(InputObject something) throws ValidationError {
    ...
    if (something.getSomeValue() < 0) {
      throw new ValidationError("I'd like this message to be passed up to the client");
    }
    ...
  }
```

I've been trying a few things, the signature of ValidationError (not to be confused with `graphql.validation.ValidationError`), and the signature looks liket his: 
```
public class ValidationError extends RuntimeException implements GraphQLError {
    ...
}
```

The "problem" is that when this error ends up in `graphql.servlet.DefaultGraphQLErrorHandler` it has already been wrapped in an `ExceptionWhileDataFetching`, meaning that `isClientError` is always `false`.

I'm having a hard time finding the place that wraps my `ValidationError` with `ExceptionWhileDataFetching`, but my guess is that I should probably implement my own `GraphQLErrorHandler`.

Not sure if this issue fits best here or in `graphql-java-utils`.

**Comment by karl-run** [comment]
It seems the `graphql.execution.SimpleDataFetcherExceptionHandler` wraps every exception to a `ExceptionWhileDataFetching`. So I guess the question becomes how to provide your own `DataFetcherExceptionHandler` to the ExecutionStrategy, and that quickly becomes a `graphql-java-utils` question.

**Comment by apottere** [comment]
Does the PR resolve this issue?

If you need more specific error handling for your project, you can always implement a [GraphQLErrorHandler](https://github.com/graphql-java/graphql-java-servlet/blob/master/src/main/java/graphql/servlet/GraphQLErrorHandler.java) and pass it to the servlet to override the default behavior.

**Comment by karl-run** [comment]
Yes, this solves our issue. Thanks for the quick merge. 

We were looking into providing our own error handler but we were having a hard time finding out how (and if) it was possible with graphql-spricg-boot-starter.

**Comment by apottere** [comment]
You should be able to just create a bean of type `GraphQLErrorHandler`
