### ISSUE TITLE
Include extensions in response.

### ISSUE THREAD

**Issue by kclaes** [graphql-java/graphql-java-servlet#55]
I'd like to include Apollo Tracing information in my reply, as documented here:
http://graphql-java.readthedocs.io/en/v6/instrumentation.html#apollo-tracing-instrumentation

It all works and I can see the data being available in the `ExecutionResult`, but the servlet only takes data and errors from the `ExecutionResult` when it builds the reply in `GraphQLServlet.createResultFromDataAndErrors`, and as such, the extension information is lost.

Can the `extensions` element be added to the reply, when it's available?

**Comment by kclaes** [comment]
I just noticed https://github.com/graphql-java/graphql-java-servlet/pull/54 ... my bad

Will this be accepted and make it into the next release? (when?)

**Comment by apottere** [comment]
This is syncing to maven centrals as `4.7.0` right now, should be available soon.
