### ISSUE TITLE
Request-scoped DataLoader

### ISSUE THREAD

**Issue by vojtechhabarta** [graphql-java/graphql-java-servlet#59]
I am trying to use DataLoaders. If I understand it correctly:
- it is recommended to create new `DataLoaderRegistry` for each user request (to prevent mixing caches for different users)
- `DataLoaderRegistry` can be stored in custom context class which is instantiated in `GraphQLServlet.createContext` (in override or using `GraphQLContextBuilder`)
- in resolvers it is possible to get `DataLoaderRegistry` from this context
- `DataLoaderDispatcherInstrumentation` must be used so that `dispatch` methods are called

but here is the problem: `DataLoaderDispatcherInstrumentation` has `DataLoaderRegistry` and it is not request-scoped.

I haven't find a way to have request-scoped `DataLoaderRegistry` so I would like to improve the servlet to allow this use case. Or am I missing something?

Methods `createContext` and `getInstrumentation` need to somehow share new `DataLoaderRegistry` (per-request) instance. One solution would be to add methods `getInstrumentation` with `GraphQLContext` parameter, delegate these methods to their parameter-less versions and call this new method from `newGraphQL` method.

If you think this would be useful I can create PR ([I already tried it](https://github.com/vojtechhabarta/graphql-java-servlet/commit/60f109305e657a5c784d78aed0405ca6ef7b53a7)). Or is there a better way?

**Comment by apottere** [comment]
Would it make sense to always add the `DataLoaderDispatcherInstrumentation` when the context has a `DataLoaderRegistry`?  i.e. should it pass the context to the `InstrumentationProvider` or should it get the instrumentation provided by the `InstrumentationProvider` and then add the `DataLoaderDispatcherInstrumentation` to it automatically?

**Comment by vojtechhabarta** [comment]
Always adding `DataLoaderDispatcherInstrumentation` when the context has a `DataLoaderRegistry` would probably make sense, I think. But I don't know what exactly you mean. Something similar to what I tried in mentioned commit? In 60f109305e657a5c784d78aed0405ca6ef7b53a7 I added `GraphQLContext` parameter to `InstrumentationProvider.getInstrumentation()` method.

Or are you thinking about supporting `DataLoaderDispatcherInstrumentation` automatically and adding `DataLoaderRegistry` field to `GraphQLContext`?

**Comment by freedomljc** [comment]
@vojtechhabarta 's diff could help the GraphQLServlet to have per-request instrumentation. 
Besides that, we need to add the dataloader into instrumentation. 
To enable dataloader per request, GraphQLContext could be the best place to instantiate the dataloaders inside. 

Ideas: 
1. Add DataLoaderRegistry into the GraphQLContext.

public class GraphQLContext {
    ....
	protected Optional<DataLoaderRegistry> dataloaderRegistry;
	public GraphQLContext(Optional<HttpServletRequest> request, Optional<HttpServletResponse> response, Optional<DataLoaderRegistry> dataloderRegistry) {
        this.request = request;
        this.response = response;
        this.dataloaderRegistry = dataloaderRegistry;
    }
    ....
}


2. Create a new class ContextA to inherit the GraphQLContext:

public class ContextA extends GraphQLContext{
	public ContextA() {
		...
		Dataloader<Object, Object> dataloaderA = new Dataloader<>();
		DataLoaderRegistry registry = new DataLoaderRegistry();
		this.registry.put("A", dataloaderA)
	}

    
	public CompleteFuture<A> loadAValue(Object key) {
		return this.registry.get("A").get(Key);
	}
}


3. Create a new class InstrumentationProviderA to inherit the InstrumentationProvider (based on @vojtechhabarta 's diff), then be able to connect the dataloader with the object .
public class InstrumentationProviderA implements InstrumentationProvider {
	public Instrumentation getInstrumentation(GraphQLContext context) {
		DataLoaderDispatcherInstrumentation dispatcherInstrumentation = new DataLoaderDispatcherInstrumentation(context.dataloaderRegistry);
		return dispatcherInstrumentation;
	}
}

**Comment by vojtechhabarta** [comment]
I would like to solve this problem somehow.

I have 2 use cases:
- Objects that can be cached regardless the user accessing the data for some amount of time. For this use case current support for DataLoaders is sufficient, moreover this can also be solved using arbitrary cache.
- Object that can be cached only per user *request*. Here I cannot use normal cache. Since the structure is relatively complex and one object can appear on different levels of result it would be really beneficial to have per-request cache.

Any idea, solution, hack...?

**Comment by vincentDAO** [comment]
@vojtechhabarta, @freedomljc I LOVE your ideas to implement "instrumentation per request" .

Our project is using @Deprecated BatchedExecutionStrategy we want to change to use DataLoader but stuck at configure DataLoader per request.

Have you guys tried to implement it?

**Comment by vojtechhabarta** [comment]
I haven't implemented it. I thought somebody who understands better than me how GraphQL in Java works should do it 😏

**Comment by ashu-walmart** [comment]
Will this PR help? https://github.com/graphql-java/graphql-java-servlet/pull/83.

**Comment by vincentDAO** [comment]
Hope it's reviewed and merged soon.
