### ISSUE TITLE
Error serializing requests with extensions (Apollo client 2.0)

### ISSUE THREAD

**Issue by ronald-d-rogers** [graphql-java/graphql-java-servlet#63]
The 2.0 version of apollo client's GraphQL requests can contain the property `extensions` which causes it to fail to deserialize to `GraphQLServlet$GraphQLRequest` because it is not also defined there.

I guess the best thing to do would be to simply ignore any unknown JSON properties.

I will go ahead and create a PR for it.

**Comment by oliemansm** [comment]
Closing since already fixed
