### ISSUE TITLE
Schema is not configured for mutations

### ISSUE THREAD

**Issue by ajcorbin** [graphql-java/graphql-java-servlet#68]
When I try to execute the mutation I get the error on the tomcat console of "Schema is not configured for mutations".  When I go to the /graphql/schema.json I am able to see the mutationType: Mutation (as in the attached image).  Somewhere there is a disconnect or a configuration issue.  I have not been able find the disconnect.  I have yet to debug the code to find the issue but wanted to see if there is something specific that I am missing before I did that. 

Snippet of schema.graphqls file.

`schema {
    mutation: Mutation
}
type Mutation {
    createComicBox( comicBoxInput: ComicBoxInput! ) : ComicBox
    removeComicBox ( comicBoxInput: ComicBoxInput! ) : ComicBox
}

type ComicBox {
    boxName: String!
}
input ComicBoxInput {
    boxName: String!
}
`

![image](https://user-images.githubusercontent.com/7208555/37485438-73c9cb9a-2859-11e8-9ed6-64fc44b8d88c.png)

I attempted to execute the mutation with the following URL snippet: /graphql?query=mutation {createComicBox(comicBoxInput:{boxName:"Song"}){boxName}}

Any help would be greatly appreciated.

**Comment by apottere** [comment]
http GET doesn't support mutations per the Usage.  Use a POST instead.

**Comment by justinnichols** [comment]
I suppose this was closed because of the assumption of using the query string parameter in the way the OP described.  However, I'm also running into this issue using POST.  I'm attempting to see if it's just a setup issue, or if there really is a problem.
