### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by bentatham** [graphql-java/graphql-java-servlet#7]
Adding a few examples or at least some getting started guides would be helpful.

**Comment by jplock** [comment]
@bentatham not sure if this is helpful or not, but I wrapped this for use in Dropwizard at https://github.com/smoketurner/dropwizard-graphql which includes an example application that uses this.

**Comment by apottere** [comment]
@bentatham I added a bunch to the README, feel free to re-open this if that doesn't cover what you needed to know.
