### ISSUE TITLE
[Question] Is "application/graphql" Content Type supported by graphql-java-servlet?

### ISSUE THREAD

**Issue by subeeshcbabu** [graphql-java/graphql-java-servlet#71]
GraphQL doc mentions `application/graphql` as one of the options to send POST requests to the server -  http://graphql.org/learn/serving-over-http/#post-request

>If the "application/graphql" Content-Type header is present, treat the HTTP POST body contents as the GraphQL query string.

This helps the client to send the query exactly like the GraphIQL tool.

I was wondering if this is something `graphql-java-servlet` supports right now or planning to support in the future?

I did try to send the request with this ContentTyope header and the Request raw body in the query format, however it did nor work.

Got the following error:

```
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'query': was expecting ('true', 'false' or 'null')
 at [Source: (BufferedInputStream); line: 1, column: 7]
```

**Comment by hangstrap** [comment]
Yes this would be helpful for us too. There is a node.js implementation of an http servlet for GraphQL that has this feature at https://github.com/graphql/express-graphql

**Comment by ashu-walmart** [comment]
I added a PR for this: https://github.com/graphql-java/graphql-java-servlet/pull/82

**Comment by oliemansm** [comment]
Thanks @ashu-walmart, just merged that PR. So should be available in the next release.
