### ISSUE TITLE
Access to servlet request in resolver?

### ISSUE THREAD

**Issue by justinnichols** [graphql-java/graphql-java-servlet#77]
I'm actually using the graphql-spring-boot-starter where it auto-maps the query/mutation to a GraphQLQueryResolver/GraphQLMutationResolver.  What I need is the ability to access the request object in order to extract certain pieces of data, such as the IP address of the requestor.

Is this possible?  If so, how would one accomplish it?

Example GraphQL schema:
```
type Login {
    token: String
}
type Mutation {
    login(username: String!, password: String!): Login
}
```

Example resolver:
```
@Component
public class LoginResolver implements GraphQLMutationResolver {
    public LoginDto login(String username, String password) {
        // Get IP address of requestor
    }
}
```

**Comment by justinnichols** [comment]
I know it's only been 6 hours or so since I posted the question, but this hinges us on a complete refactor away from using graphql-java-servlet and simply using graphql-java with a standard `@RestController`.  I'd much rather use the Spring Boot starter with graphql-java-servlet because it's quite elegant.  However, if I cannot get certain data about the request as well, at the time of the request occurring, then this is much more of an abstraction than we'll be able to use.

**Comment by oliemansm** [comment]
You can add the optional `DataFetchingEnvironment` as last parameter to your query/mutation method and grab it from the context like this:
```
@Component
public class LoginResolver implements GraphQLMutationResolver {
    public LoginDto login(String username, String password, DataFetchingEnvironment environment) {
        // Get IP address of requestor
        GraphQLContext context = environment.getContext();
        String ipAddress = context.getRequest().get().getRemoteAddr();
    }
}
```

**Comment by justinnichols** [comment]
You are a life saver.  Thank you!  I'm sorry if this was in some documentation that I did not find, and I was hoping it was that simple.  Very much appreciated!

**Comment by oliemansm** [comment]
No problem, glad it helped. You can find more about this in this readme: https://github.com/graphql-java/graphql-java-tools. The complete GraphQL solution in Java is split in a couple of projects, so when you're facing an issue it's a bit of searching which project you need to look into.
