### ISSUE TITLE
Unable to set status code

### ISSUE THREAD

**Issue by dan-j** [graphql-java/graphql-java-servlet#79]
Happy to make a pull request with the below solution, let me know your thoughts...

I'm using this with the spring-boot starter and would like to make use of `@ResponseStatus` on my exceptions to set the status code. 

The only thing from preventing this to work nicely is being unable to set the status code programatically. 

TL;DR - I suggest changing `GraphQLServlet#query` as such: 

```java
GraphQLResponse graphQLResponse = new GraphQLResponse();
graphQLResponse.setStatus(STATUS_OK);
graphQLResponse.setResponse(response);

if(getGraphQLErrorHandler().errorsPresent(errors)) {
    // note graphQLResponse is passed to the callback
    runCallbacks(operationCallbacks, c -> c.onError(context, operationName, query, variables, data, errors, graphQLResponse));
} else {
    // note graphQLResponse is passed to the callback
    runCallbacks(operationCallbacks, c -> c.onSuccess(context, operationName, query, variables, data, graphQLResponse));
}

responseHandler.handle(graphQLResponse);
```

This would allow `GraphQLServletListener.OperationCallback` instances to be registered to change the status code before it's written to the underlying response.

---

_What I've already tried_

The response is hardcoded to `STATUS_OK` and the only other place you can get access to both the response and throwable objects is in the `GraphQLServletListener.RequestCallback.onError(...)` method, however I can't see a way of throwing an exception up to `GraphQLServlet.doRequest(...)`. I tried implementing an `GraphQLServletListener.OperationCallback` but these are wrapped in a silenced try/catch. 

The only place to throw would be in the `GraphQLErrorHandler.processErrors(...)`, but I want to keep the graphql error JSON format and throwing an exception here would prevent the response body being written.

I suggest the `GraphQLServletListener.OperationCallback` methods should get access to the `GraphQLResponse` object before being handled by the `GraphQLServlet.GraphQLResponseHandler` parameter.

**Comment by oliemansm** [comment]
@dan-j I understand why you would want to do that, but I believe that goes against the principles of GraphQL. Because it's possible to have (for example) 3 named queries in one request, of which 2 succeed and only 1 fails. The error message is tied specifically to the failed query, so you can handle it that way. You could add a custom error handler to provide more detail or extra fields if you want to be able to handle those errors better. That's something already supported.

**Comment by oliemansm** [comment]
@dan-j See this article for more details about http status codes and errors and why you shouldn't do this: https://medium.com/impraise-design-engineering/making-mistakes-with-graphql-874b8ca62b9d.

**Comment by dan-j** [comment]
@oliemansm yes I completely agree with you know you’ve pointed it out. I forgot to reply to your first comment, your second just reminded me it was still open.

Happy to close this
