### ISSUE TITLE
Cannot Resolve Symbol SimpleGraphQLServlet

### ISSUE THREAD

**Issue by RayOconnor** [graphql-java/graphql-java-servlet#90]
I must be missing something quite simple. I am attempting to follow the tutorial [here](https://www.howtographql.com/graphql-java/1-getting-started/) which would like me to extend `SimpleGraphQLServlet`. When I try to import this class I get a cannot resolve symbol error though. 

This is strange as some of the examples in the readme make use of this class. 

My mvn dependency looks like this...

```
<dependency>
      <groupId>com.graphql-java</groupId>
      <artifactId>graphql-java-servlet</artifactId>
      <version>6.0.0</version>
</dependency>
```

and I have no trouble importing classes like `SimpleGraphQLHttpServlet`.

**Comment by oliemansm** [comment]
In version 6.0.0 the `SimpleGraphQLServlet` has been renamed to `SimpleGraphQLHttpServlet`. This is quite a recent change. So probably using that should get you going.

**Comment by RayOconnor** [comment]
@oliemansm Thanks for the lightning fast response. 

I tried substituting `SimpleGraphQLHttpServlet ` for `SimpleGraphQLServlet`, but the constructor has private access and the tutorial calls for me to extend the class. Your comment gives me more confidence to tinker some more with `SimpleGraphQLHttpServlet `. I'll mess around and see what I can come up with, if all else fails I can always just use a previous version that supports `SimpleGraphQLServlet`

**Comment by jplock** [comment]
I just did this upgrade myself yesterday if it’s of any help. https://github.com/smoketurner/dropwizard-graphql/commit/912bf9f34d04c00635e3b56522b1bb9f932dc394

**Comment by RayOconnor** [comment]
Thanks for the help. This should be more than sufficient for me to get going. Much appreciated.

**Comment by MatheusArleson** [comment]
The solutions you provide:
1) Understand another repo code
2) Extend one abstraction
3) Integrate another framework

1 and 3) Really? The very first line of code and I already have to lookup for issues on github?
2) It is an abstraction! And the _Simple_ impl should be... simple.

Why not improve the documentation and examples? Please tell us how to get started, and use the library.

Not even the release notes states the breaking changes. It makes hard to do fixes.

Unless the readme is updated, this issue should no be closed.
