### ISSUE TITLE
GraphQLJavaServlet

### ISSUE THREAD

**Issue by sra-013** [graphql-java/graphql-java-servlet#99]
What is the replacement for SimpleGraphQLServlet (along with the required parameters to the constructor) in the latest release?

**Comment by alamothe** [comment]
I see `SimpleGraphQLHttpServlet` but the constructor is private again, which makes it useless inside a servlet container.

**Comment by oliemansm** [comment]
You have to use the builder now to construct a `SimpleGraphQLHttpServlet`, e.g.:
```java
private SimpleGraphQLHttpServlet createServlet(GraphQLSchema schema) {
  GraphQLSchemaProvider schemaProvider = new DefaultGraphQLSchemaProvider(schema);
  GraphQLInvocationInputFactory invocationInputFactory = GraphQLInvocationInputFactory.newBuilder(schemaProvider).build();
  return SimpleGraphQLHttpServlet.newBuilder(invocationInputFactory).build();
}
```

@alamothe To be able to use it in a servlet container you probably need #60 which is yet to be implemented.

**Comment by alamothe** [comment]
@oliemansm It only needs constructor to be protected (it was in 5.0.1)

I don't understand why this is such a huge issue.

I'm sticking with 5.0.1 for now

**Comment by oliemansm** [comment]
@alamothe Who's saying it's a huge issue? Made it protected again.

**Comment by alamothe** [comment]
@oliemansm My apologies, I wrongly assumed it was made private again on purpose and there's a reason to keep it that way.

Thanks for doing this!

**Comment by oliemansm** [comment]
Sure, no problem. Not sure if this one will be part of 5.0.3 or the release after that. Depends on if the 5.0.3 release was already in the pipeline at Sonatype.

**Comment by MarkNenadov** [comment]
@oliemansm is there I way you can do things like append a cookie to the response or create a custom error handling strategy with this createServlet method example you showed? That's what I'm struggling with. I used to extend SimpleGraphQLServlet's methods like createContext and getGraphQLErrorHandler, but now its not clear to me how that works with a GraphQLInvocationInputFactor. The documentation here on github is out of date (it still refers to SimpleGraphQLServlet.

**Comment by khteh** [comment]
The `.build()` method is indicated as `@deprecated` in the IDE. What's the change? How to instantiate it?
